<?php
/**
 * ServerPostRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * VDSina public API
 *
 * The data format of the incoming request and the returned data: JSON. All dates and timestamps are returned in the Europe/Moscow zone (the time zone in which the API server is located). A permanent authorization token can be obtained in the personal account in viewing the user's account information. The token changes when the user's password is changed. The token will have the same access rights as the specified user on whose behalf the token request was made. If you need to restrict actions for API requests, you need to create a separate user in the account with the necessary set of rights and make requests with this user's token.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@vdsina.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServerPostRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServerPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_server_post_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'datacenter' => 'int',
        'server_plan' => 'int',
        'template' => 'int',
        'backup' => 'int',
        'schedule' => 'string',
        'ssh_key' => 'int',
        'iso' => 'int',
        'host' => 'string',
        'cpu' => 'int',
        'ram' => 'int',
        'disk' => 'int',
        'gpu' => 'int',
        'ip4' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'datacenter' => null,
        'server_plan' => null,
        'template' => null,
        'backup' => null,
        'schedule' => null,
        'ssh_key' => null,
        'iso' => null,
        'host' => null,
        'cpu' => null,
        'ram' => null,
        'disk' => null,
        'gpu' => null,
        'ip4' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => true,
        'datacenter' => false,
        'server_plan' => false,
        'template' => true,
        'backup' => true,
        'schedule' => true,
        'ssh_key' => true,
        'iso' => true,
        'host' => true,
        'cpu' => true,
        'ram' => true,
        'disk' => true,
        'gpu' => true,
        'ip4' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'datacenter' => 'datacenter',
        'server_plan' => 'server-plan',
        'template' => 'template',
        'backup' => 'backup',
        'schedule' => 'schedule',
        'ssh_key' => 'ssh-key',
        'iso' => 'iso',
        'host' => 'host',
        'cpu' => 'cpu',
        'ram' => 'ram',
        'disk' => 'disk',
        'gpu' => 'gpu',
        'ip4' => 'ip4'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'datacenter' => 'setDatacenter',
        'server_plan' => 'setServerPlan',
        'template' => 'setTemplate',
        'backup' => 'setBackup',
        'schedule' => 'setSchedule',
        'ssh_key' => 'setSshKey',
        'iso' => 'setIso',
        'host' => 'setHost',
        'cpu' => 'setCpu',
        'ram' => 'setRam',
        'disk' => 'setDisk',
        'gpu' => 'setGpu',
        'ip4' => 'setIp4'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'datacenter' => 'getDatacenter',
        'server_plan' => 'getServerPlan',
        'template' => 'getTemplate',
        'backup' => 'getBackup',
        'schedule' => 'getSchedule',
        'ssh_key' => 'getSshKey',
        'iso' => 'getIso',
        'host' => 'getHost',
        'cpu' => 'getCpu',
        'ram' => 'getRam',
        'disk' => 'getDisk',
        'gpu' => 'getGpu',
        'ip4' => 'getIp4'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCHEDULE__0 = '0';
    public const SCHEDULE__1 = '1';
    public const IP4__0 = '0';
    public const IP4__1 = '1';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScheduleAllowableValues()
    {
        return [
            self::SCHEDULE__0,
            self::SCHEDULE__1,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIp4AllowableValues()
    {
        return [
            self::IP4__0,
            self::IP4__1,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('datacenter', $data ?? [], null);
        $this->setIfExists('server_plan', $data ?? [], null);
        $this->setIfExists('template', $data ?? [], null);
        $this->setIfExists('backup', $data ?? [], null);
        $this->setIfExists('schedule', $data ?? [], '1');
        $this->setIfExists('ssh_key', $data ?? [], null);
        $this->setIfExists('iso', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('cpu', $data ?? [], null);
        $this->setIfExists('ram', $data ?? [], null);
        $this->setIfExists('disk', $data ?? [], null);
        $this->setIfExists('gpu', $data ?? [], null);
        $this->setIfExists('ip4', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['datacenter'] === null) {
            $invalidProperties[] = "'datacenter' can't be null";
        }
        if ($this->container['server_plan'] === null) {
            $invalidProperties[] = "'server_plan' can't be null";
        }
        $allowedValues = $this->getScheduleAllowableValues();
        if (!is_null($this->container['schedule']) && !in_array($this->container['schedule'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schedule', must be one of '%s'",
                $this->container['schedule'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIp4AllowableValues();
        if (!is_null($this->container['ip4']) && !in_array($this->container['ip4'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ip4', must be one of '%s'",
                $this->container['ip4'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Server name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets datacenter
     *
     * @return int
     */
    public function getDatacenter()
    {
        return $this->container['datacenter'];
    }

    /**
     * Sets datacenter
     *
     * @param int $datacenter Datacenter ID
     *
     * @return self
     */
    public function setDatacenter($datacenter)
    {
        if (is_null($datacenter)) {
            throw new \InvalidArgumentException('non-nullable datacenter cannot be null');
        }
        $this->container['datacenter'] = $datacenter;

        return $this;
    }

    /**
     * Gets server_plan
     *
     * @return int
     */
    public function getServerPlan()
    {
        return $this->container['server_plan'];
    }

    /**
     * Sets server_plan
     *
     * @param int $server_plan Tariff plan ID
     *
     * @return self
     */
    public function setServerPlan($server_plan)
    {
        if (is_null($server_plan)) {
            throw new \InvalidArgumentException('non-nullable server_plan cannot be null');
        }
        $this->container['server_plan'] = $server_plan;

        return $this;
    }

    /**
     * Gets template
     *
     * @return int|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param int|null $template OS template ID, mutually exclusive parameter with backup
     *
     * @return self
     */
    public function setTemplate($template)
    {
        if (is_null($template)) {
            array_push($this->openAPINullablesSetToNull, 'template');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('template', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets backup
     *
     * @return int|null
     */
    public function getBackup()
    {
        return $this->container['backup'];
    }

    /**
     * Sets backup
     *
     * @param int|null $backup ID of the backup service, mutually exclusive parameter with template. The backup must be located in the same data center as the server being created and be no larger than the disk size of the selected tariff plan
     *
     * @return self
     */
    public function setBackup($backup)
    {
        if (is_null($backup)) {
            array_push($this->openAPINullablesSetToNull, 'backup');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('backup', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['backup'] = $backup;

        return $this;
    }

    /**
     * Gets schedule
     *
     * @return string|null
     */
    public function getSchedule()
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param string|null $schedule 0 or 1, for create automatic backup week schedule for server. First copy will be created the next day after service created
     *
     * @return self
     */
    public function setSchedule($schedule)
    {
        if (is_null($schedule)) {
            array_push($this->openAPINullablesSetToNull, 'schedule');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('schedule', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getScheduleAllowableValues();
        if (!is_null($schedule) && !in_array($schedule, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schedule', must be one of '%s'",
                    $schedule,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schedule'] = $schedule;

        return $this;
    }

    /**
     * Gets ssh_key
     *
     * @return int|null
     */
    public function getSshKey()
    {
        return $this->container['ssh_key'];
    }

    /**
     * Sets ssh_key
     *
     * @param int|null $ssh_key SSH key ID for root user in the supported OS, ignored in case of recovery from backup
     *
     * @return self
     */
    public function setSshKey($ssh_key)
    {
        if (is_null($ssh_key)) {
            array_push($this->openAPINullablesSetToNull, 'ssh_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ssh_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ssh_key'] = $ssh_key;

        return $this;
    }

    /**
     * Gets iso
     *
     * @return int|null
     */
    public function getIso()
    {
        return $this->container['iso'];
    }

    /**
     * Sets iso
     *
     * @param int|null $iso ID of the ISO service, mutually exclusive parameter with template
     *
     * @return self
     */
    public function setIso($iso)
    {
        if (is_null($iso)) {
            array_push($this->openAPINullablesSetToNull, 'iso');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('iso', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['iso'] = $iso;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host Server hostname, must be correct domain name, ignored in case of recovery from backup
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            array_push($this->openAPINullablesSetToNull, 'host');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('host', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets cpu
     *
     * @return int|null
     */
    public function getCpu()
    {
        return $this->container['cpu'];
    }

    /**
     * Sets cpu
     *
     * @param int|null $cpu Number of virtual CPUs, if tariff plan supports parameter settings
     *
     * @return self
     */
    public function setCpu($cpu)
    {
        if (is_null($cpu)) {
            array_push($this->openAPINullablesSetToNull, 'cpu');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cpu', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cpu'] = $cpu;

        return $this;
    }

    /**
     * Gets ram
     *
     * @return int|null
     */
    public function getRam()
    {
        return $this->container['ram'];
    }

    /**
     * Sets ram
     *
     * @param int|null $ram Amount of RAM in GBs, if tariff plan supports parameter settings
     *
     * @return self
     */
    public function setRam($ram)
    {
        if (is_null($ram)) {
            array_push($this->openAPINullablesSetToNull, 'ram');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ram', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ram'] = $ram;

        return $this;
    }

    /**
     * Gets disk
     *
     * @return int|null
     */
    public function getDisk()
    {
        return $this->container['disk'];
    }

    /**
     * Sets disk
     *
     * @param int|null $disk Amount of storage in GBs, if tariff plan supports parameter settings
     *
     * @return self
     */
    public function setDisk($disk)
    {
        if (is_null($disk)) {
            array_push($this->openAPINullablesSetToNull, 'disk');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disk', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disk'] = $disk;

        return $this;
    }

    /**
     * Gets gpu
     *
     * @return int|null
     */
    public function getGpu()
    {
        return $this->container['gpu'];
    }

    /**
     * Sets gpu
     *
     * @param int|null $gpu Number of GPUs, if tariff plan supports parameter settings
     *
     * @return self
     */
    public function setGpu($gpu)
    {
        if (is_null($gpu)) {
            array_push($this->openAPINullablesSetToNull, 'gpu');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gpu', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gpu'] = $gpu;

        return $this;
    }

    /**
     * Gets ip4
     *
     * @return string|null
     */
    public function getIp4()
    {
        return $this->container['ip4'];
    }

    /**
     * Sets ip4
     *
     * @param string|null $ip4 0 or 1, for order IPv4 for server, if tariff plan supports parameter settings
     *
     * @return self
     */
    public function setIp4($ip4)
    {
        if (is_null($ip4)) {
            array_push($this->openAPINullablesSetToNull, 'ip4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getIp4AllowableValues();
        if (!is_null($ip4) && !in_array($ip4, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ip4', must be one of '%s'",
                    $ip4,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ip4'] = $ip4;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


